# Generated by Django 2.0.7 on 2018-09-01 15:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2018, 9, 1, 15, 58, 54, 979928, tzinfo=utc))),
            ],
        ),
    ]
