# Generated by Django 2.0.7 on 2018-09-01 16:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 1, 16, 1, 8, 401040, tzinfo=utc)),
        ),
    ]
