# Generated by Django 2.0.7 on 2018-09-01 15:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20180901_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 1, 15, 58, 54, 955998, tzinfo=utc)),
        ),
    ]
